### ISSUE TITLE
[timeout] Forbidden error when tt or utt a user if they have a role higher than the bot

### ISSUE THREAD

**Issue by NoobInDaHause** [sravan1946/sravan-cogs#24]
```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/BaconMan/cogs/CogManager/cogs/timeout/timeout.py", line 190, in timeout
    await self.timeout_user(ctx, member_or_role, time, reason)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/BaconMan/cogs/CogManager/cogs/timeout/timeout.py", line 92, in timeout_user
    await ctx.bot.http.request(r, json=payload, reason=reason)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

**Comment by sravan1946** [comment]
I will be doing a small rewrite of the timeout cog for the dpy2 branch and this should be fixed there

**Comment by NoobInDaHause** [comment]
looking forward to it

**Comment by sravan1946** [comment]
should be fixed now
